#!/usr/bin/env pwsh
<#
.SYNOPSIS
    build.ps1 - a shim. Every target is implemented in make.js; run .\build.ps1 for the list.

.DESCRIPTION
    Why a shim and not the implementation: Windows does not ship make and macOS does not
    ship PowerShell, while both must already have Node (package.json pins >= 20.12). So the
    logic lives in one Node file that gets linted and tested with the rest of the project,
    and this file plus the Makefile exist only so the habitual invocation works on each
    platform. Adding a target never means editing this file.

    Unlike the Makefile, this passes arguments through untouched: raw --flags and bare
    key=value words both work.

        .\build.ps1 dry-run "@SomeChannel"
        .\build.ps1 run "@SomeChannel" --max=1
        .\build.ps1 add-channel "@SomeChannel" shorts=split

    QUOTE THE HANDLE. Bare @SomeChannel is not text to PowerShell - @ begins a splatting
    expression, so an undefined variable expands to an empty argument and the handle
    vanishes without an error. On `run` that is the difference between syncing one channel
    and syncing all of them, so make.js refuses an empty argument rather than guessing.

    Targets are defined in make.js, not here; this file forwards whatever it is given.
    The list below is generated by `.\build.ps1 sync-shims` and verified by
    `.\build.ps1 check`, so it is safe to read but pointless to edit.

    # >>> targets >>>
    #   Setting up
    #     setup            install dependencies, enable the pre-push hook, create .env and channels.txt
    #     authorize        one-time Google OAuth in a browser; writes GOOGLE_REFRESH_TOKEN to .env
    #     change-email     set REPORT_TO in .env - who receives the run report
    #     doctor           check this checkout can run at all: node, credentials, channel list, hooks
    #   Running the sync
    #     dry-run          read everything, write nothing - always the first thing to run
    #     run              sync for real: every channel in config/channels.txt, or just the one named
    #     nightly          exactly what the scheduled job runs (--email-on-change), by hand
    #     watchdog         staleness check; emails ERROR_ALERT_TO if no sync has finished in 36h
    #     watchdog-dry     the same check with nothing sent
    #   Channels
    #     list-channels    the configured channels and the playlists each one asks for
    #     add-channel      append a validated line to config/channels.txt
    #     remove-channel   drop a line from config/channels.txt (leaves the playlist and ledger alone)
    #   The account
    #     claim            take this account’s sync marker over from another machine (50 quota units)
    #     unclaim          give this machine’s claim up, so another machine can take the account
    #     unclaim-all      clear every claim on the account - the next machine to sync takes it
    #   Quality
    #     test             the full node:test suite
    #     lint             eslint, --max-warnings=0
    #     check            everything lint and the tests cannot see: secrets, manifest, links, endings
    #     ci               lint, tests and every check - what the pre-push hook runs. Reports all failures
    #     sync-shims       regenerate the target list inside Makefile and build.ps1
    #   The scheduled job
    #     status           is the nightly job installed, and when did a sync last finish
    #     install          register the nightly sync and the watchdog (needs sudo, once)
    #     uninstall        remove both scheduled jobs; state/, logs/ and the playlists are untouched
    #     change-run-time  move the nightly sync (the watchdog follows, six hours later)
    #     run-now          trigger the scheduled sync immediately, through the scheduler itself
    #   Housekeeping
    #     report           open the last run’s report.html
    #     logs             the tail of logs/sync.log (default 40 lines)
    #     clean            delete logs/ and report.html - never state/, which holds the watched ledger
    #     version          what this checkout is: package version, commit, node, platform
    #     help             this list
    # <<< targets <<<

.NOTES
    If Windows refuses to run this ("running scripts is disabled on this system"), either
    allow local scripts once:

        Set-ExecutionPolicy -Scope CurrentUser RemoteSigned

    or bypass it per call:

        powershell -NoProfile -ExecutionPolicy Bypass -File .\build.ps1 help
#>

$ErrorActionPreference = 'Stop'

# Resolve node the same way run-sync.cmd does: PATH first, then the default installer
# location, because a shell started before the installer's PATH entry is visible to it
# finds nothing and the error names the script rather than the missing runtime.
$nodeExe = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $nodeExe) {
    $fallback = Join-Path ${env:ProgramFiles} 'nodejs\node.exe'
    if (Test-Path $fallback) { $nodeExe = $fallback }
}
if (-not $nodeExe) {
    Write-Host ''
    Write-Host 'node was not found on PATH or in Program Files\nodejs.' -ForegroundColor Red
    Write-Host 'Install Node 20.12 or newer from https://nodejs.org and reopen this shell.'
    Write-Host ''
    exit 127
}

# Catch the splatting mistake here, because it cannot be caught later: PowerShell drops
# empty strings when it builds an external process's argument list, so an unquoted
# @SomeChannel reaches this script as an empty element of $args and reaches node as
# nothing at all. By the time make.js runs, `run @SomeChannel` and `run` are identical -
# and the second one syncs every channel in the list. Verified on pwsh 7.6.
# Splatting an undefined variable yields $null, not an empty string, so both are tested.
# -contains rather than a Where-Object pipeline: the pipeline matches correctly but then
# emits the $null it matched, and `if ($null)` is false - a guard that silently never
# fires, which is the exact failure shape it was written to catch.
if (($args -contains $null) -or ($args -contains '')) {
    Write-Host ''
    Write-Host 'One argument arrived empty.' -ForegroundColor Red
    Write-Host 'In PowerShell @ begins a splatting expression, so a bare @Handle is not text:'
    Write-Host 'an undefined variable expands to nothing and the handle disappears silently.'
    Write-Host 'Quote it:  .\build.ps1 run "@SomeChannel"'
    Write-Host ''
    exit 1
}

& $nodeExe (Join-Path $PSScriptRoot 'make.js') @args
exit $LASTEXITCODE
