# Makefile - a shim. Every target is implemented in make.js; run `make` for the list.
#
# Why a shim and not the implementation: Windows does not ship make and macOS does not
# ship PowerShell, while both must already have Node (package.json pins >= 20.12). So the
# logic lives in one Node file that gets linted and tested with the rest of the project,
# and this file plus build.ps1 exist only so the habitual invocation works on each
# platform. Adding a target never means editing this file.
#
# Passing arguments
#   make dry-run "@SomeChannel"          bare words arrive as goals
#   make add-channel "@X" shorts=split   key=value words arrive via MAKEOVERRIDES
#   make run ARGS='--report-watched'     raw flags, which make would otherwise eat
#
# A raw --flag cannot be written on a make command line: make claims those for itself,
# and the two it takes SILENTLY are the two that matter. `--dry-run` puts make into its
# own -n mode, so the recipe is echoed and nothing runs at all - which reads as a dry run
# that worked. `--max=1` is matched as an abbreviation of make's --max-load and becomes
# `-l 1`, so the cap on writes against a live account disappears without a word. Hence
# the key=value spelling, and hence the `+` below.

# The targets live in make.js, not here - this file forwards every goal through one
# generic rule, which is why no target is named below the marker block. The list is
# generated by `make sync-shims`, and `make check` fails when it has drifted, so it is
# safe to read but pointless to edit.
#
# >>> targets >>>
#   Setting up
#     setup            install dependencies, enable the pre-push hook, create .env and channels.txt
#     authorize        one-time Google OAuth in a browser; writes GOOGLE_REFRESH_TOKEN to .env
#     change-email     set REPORT_TO in .env - who receives the run report
#     doctor           check this checkout can run at all: node, credentials, channel list, hooks
#   Running the sync
#     dry-run          read everything, write nothing - always the first thing to run
#     run              sync for real: every channel in config/channels.txt, or just the one named
#     nightly          exactly what the scheduled job runs (--email-on-change), by hand
#     watchdog         staleness check; emails ERROR_ALERT_TO if no sync has finished in 36h
#     watchdog-dry     the same check with nothing sent
#   Channels
#     list-channels    the configured channels and the playlists each one asks for
#     add-channel      append a validated line to config/channels.txt
#     remove-channel   drop a line from config/channels.txt (leaves the playlist and ledger alone)
#   The account
#     claim            take this account’s sync marker over from another machine (50 quota units)
#     unclaim          give this machine’s claim up, so another machine can take the account
#     unclaim-all      clear every claim on the account - the next machine to sync takes it
#   Quality
#     test             the full node:test suite
#     lint             eslint, --max-warnings=0
#     check            everything lint and the tests cannot see: secrets, manifest, links, endings
#     ci               lint, tests and every check - what the pre-push hook runs. Reports all failures
#     sync-shims       regenerate the target list inside Makefile and build.ps1
#   The scheduled job
#     status           is the nightly job installed, and when did a sync last finish
#     install          register the nightly sync and the watchdog (needs sudo, once)
#     uninstall        remove both scheduled jobs; state/, logs/ and the playlists are untouched
#     change-run-time  move the nightly sync (the watchdog follows, six hours later)
#     run-now          trigger the scheduled sync immediately, through the scheduler itself
#   Housekeeping
#     report           open the last run’s report.html
#     logs             the tail of logs/sync.log (default 40 lines)
#     clean            delete logs/ and report.html - never state/, which holds the watched ledger
#     from-release     set a release kit up on a machine with no dev tooling: deps, .env, channels, next steps
#     release          cut a release: name the Unreleased section after HEAD, tag it, publish it on GitHub
#     version          what this checkout is: package version, commit, node, platform
#     help             this list
# <<< targets <<<

.DEFAULT_GOAL := help

GOALS = $(if $(MAKECMDGOALS),$(MAKECMDGOALS),help)
FIRST = $(firstword $(GOALS))
REST  = $(wordlist 2,$(words $(GOALS)),$(GOALS))

# Command-line `key=value` words are variable assignments rather than goals, so they land
# here instead of in MAKECMDGOALS. ARGS is our own escape hatch, so it must not be
# forwarded twice.
SETTINGS = $(filter-out ARGS=%,$(MAKEOVERRIDES))

# .PHONY because config/, docs/, logs/, state/ and test/ are real directories: without it
# `make test` finds the directory, decides it is already up to date, and does nothing at
# all while printing something that looks like success.
.PHONY: $(GOALS)

# The leading `+` runs this recipe even under make -n, which is what lets make.js report a
# swallowed --dry-run instead of make silently echoing the line and skipping it.
$(FIRST):
	+@node make.js $(GOALS) $(SETTINGS) $(ARGS)

# Every word after the first is an argument, already forwarded above. These rules exist so
# make does not try to build them, and do nothing.
ifneq ($(REST),)
$(REST):
	@:
endif
